/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 8.0.41 : Database - sitea4.0
*********************************************************************
*/


/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`sitea4.0` /*!40100 DEFAULT CHARACTER SET utf8mb4 */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `sitea4.0`;

/*Table structure for table `actividad_clase` */

DROP TABLE IF EXISTS `actividad_clase`;

CREATE TABLE `actividad_clase` (
  `ID_ACTIVIDAD_CLASE` INT NOT NULL AUTO_INCREMENT,
  `PIAR_CODIGO_PIAR` INT NOT NULL,
  `PERIODO_ACTIVIDAD_CLASE` VARCHAR(45) NOT NULL,
  `FECHA_ACTIVIDAD_CLASE` DATE NOT NULL,
  `DUA_ACTIVIDAD_CLASE` VARCHAR(200) NOT NULL,
  `DESCRIPCION_ACTIVIDAD_CLASE` VARCHAR(500) NOT NULL,
  `DIARIO_PEDAGOGICO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_ACTIVIDAD_CLASE`),
  KEY `PIAR_CODIGO_PIAR` (`PIAR_CODIGO_PIAR`),
  CONSTRAINT `actividad_clase_ibfk_1` FOREIGN KEY (`PIAR_CODIGO_PIAR`) REFERENCES `piar` (`CODIGO_PIAR`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

/*Data for the table `actividad_clase` */

LOCK TABLES `actividad_clase` WRITE;

UNLOCK TABLES;

/*Table structure for table `boletin_académico` */

DROP TABLE IF EXISTS `boletin_académico`;

CREATE TABLE `boletin_académico` (
  `ID_BOLETIN_ACADÉMICO` INT NOT NULL AUTO_INCREMENT,
  `FECHA_BOLETIN` DATE NOT NULL,
  `PERIODO_BOLETIN` VARCHAR(45) NOT NULL,
  `OBSERVACIÓN_PROF` VARCHAR(45) NOT NULL,
  `ESTADO_BOLETIN` VARCHAR(45) DEFAULT NULL,
  `DESEMPEÑO` VARCHAR(45) NOT NULL,
  `RECOMENDACIONES` VARCHAR(45) DEFAULT NULL,
  `NOVEDADES_ REPORTES_ID_NOVEDADES_REPORTES` INT NOT NULL,
  `ESTUDIANTE_ID_ESTUDIANTE` INT NOT NULL,
  PRIMARY KEY (`ID_BOLETIN_ACADÉMICO`),
  KEY `NOVEDADES_ REPORTES_ID_NOVEDADES_REPORTES` (`NOVEDADES_ REPORTES_ID_NOVEDADES_REPORTES`),
  KEY `ESTUDIANTE_ID_ESTUDIANTE` (`ESTUDIANTE_ID_ESTUDIANTE`),
  CONSTRAINT `boletin_académico_ibfk_1` FOREIGN KEY (`NOVEDADES_ REPORTES_ID_NOVEDADES_REPORTES`) REFERENCES `novedades_ reportes` (`ID_NOVEDADES_REPORTES`),
  CONSTRAINT `boletin_académico_ibfk_2` FOREIGN KEY (`ESTUDIANTE_ID_ESTUDIANTE`) REFERENCES `estudiante` (`ID_ESTUDIANTE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

/*Data for the table `boletin_académico` */

LOCK TABLES `boletin_académico` WRITE;

UNLOCK TABLES;

/*Table structure for table `caracterizacion` */

DROP TABLE IF EXISTS `caracterizacion`;

CREATE TABLE `caracterizacion` (
  `ID_CARACTERIZACION` INT NOT NULL AUTO_INCREMENT,
  `CODIGO_CARACTERIZACION` INT NOT NULL,
  `ESTUDIANTE_ID_ESTUDIANTE` INT NOT NULL,
  `CONTEXTO_ACADEMICO` VARCHAR(200) NOT NULL,
  `CONTEXTO_FAMILIAR` VARCHAR(200) NOT NULL,
  `CONTEXTO_ESCOLAR` VARCHAR(200) NOT NULL,
  `DIAGNOSTICO` VARCHAR(255) NOT NULL,
  `VALORACION_PEDAGOGICA` VARCHAR(300) NOT NULL,
  `BARRA_DE_APRENDIZAJE` VARCHAR(200) NOT NULL,
  `RECOMENDACIONES` VARCHAR(500) NOT NULL,
  `CORRESPONSABILIDAD` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID_CARACTERIZACION`),
  CONSTRAINT `caracterizacion_ibfk_1` FOREIGN KEY (`ESTUDIANTE_ID_ESTUDIANTE`) REFERENCES `estudiante` (`ID_ESTUDIANTE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

/*Data for the table `caracterizacion` */

LOCK TABLES `caracterizacion` WRITE;

UNLOCK TABLES;

/*Table structure for table `estrategias_educativas` */

DROP TABLE IF EXISTS `estrategias_educativas`;

CREATE TABLE `estrategias_educativas` (
  `ID_ESTRATEGIAS_EDUCATIVAS` INT NOT NULL AUTO_INCREMENT,
  `CODIGO_ESTRATEGIAS_EDUCATIVAS` VARCHAR(45) NOT NULL,
  `TIPO_ESTRATEGIAS_EDUCATIVAS` VARCHAR(45) NOT NULL,
  `DESCRIPCION_ESTRATEGIA` VARCHAR(300) NOT NULL,
  `HERRAMIENTAS_ESTRATEGIA` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_ESTRATEGIAS_EDUCATIVAS`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

/*Data for the table `estrategias_educativas` */

LOCK TABLES `estrategias_educativas` WRITE;

UNLOCK TABLES;

/*Table structure for table `estudiante` */

DROP TABLE IF EXISTS `estudiante`;

CREATE TABLE `estudiante` (
  `ID_ESTUDIANTE` INT NOT NULL AUTO_INCREMENT,
  `NUMERO_DOCUMENTO_ESTUDIANTE` VARCHAR(20) NOT NULL,
  `PRIMER_NOMBRE_ESTUDIANTE` VARCHAR(45) NOT NULL,
  `SEGUNDO_NOMBRE_ESTUDIANTE` VARCHAR(45) DEFAULT NULL,
  `PRIMER_APELLIDO_ESTUDIANTE` VARCHAR(45) NOT NULL,
  `SEGUNDO_APELLIDO_ESTUDIANTE` VARCHAR(45) DEFAULT NULL,
  `FECHA_NACIMIENTO` DATE NOT NULL,
  `TELEFONO_ESTUDIANTE` VARCHAR(20) DEFAULT NULL,
  `DIRECCION_ESTUDIANTE` TINYTEXT NOT NULL,
  `CORREO_INSTITUCIONAL_ESTUDIANTE` VARCHAR(45) NOT NULL,
  `FOTOGRAFIA_ESTUDIANTE` MEDIUMBLOB NOT NULL,
  `numero_documento_padre` VARCHAR(45) DEFAULT NULL,
  `TIPO_DOCUMENTO_ID_TIPO_DOCUMENTO` int NOT NULL,
  PRIMARY KEY (`ID_ESTUDIANTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `estudiante` */

LOCK TABLES `estudiante` WRITE;

UNLOCK TABLES;

/*Table structure for table `estudiante_has_trastorno` */

DROP TABLE IF EXISTS `estudiante_has_trastorno`;

CREATE TABLE `estudiante_has_trastorno` (
  `ID_ESTUDIANTE_has_TRASTORNO` int NOT NULL AUTO_INCREMENT,
  `ESTUDIANTE_ID_ESTUDIANTE` int NOT NULL,
  `TRASTORNO_ID_TRASTORNO` int NOT NULL,
  PRIMARY KEY (`ID_ESTUDIANTE_has_TRASTORNO`),
  KEY `ESTUDIANTE_ID_ESTUDIANTE` (`ESTUDIANTE_ID_ESTUDIANTE`),
  KEY `TRASTORNO_ID_TRASTORNO` (`TRASTORNO_ID_TRASTORNO`),
  CONSTRAINT `estudiante_has_trastorno_ibfk_1` FOREIGN KEY (`ESTUDIANTE_ID_ESTUDIANTE`) REFERENCES `estudiante` (`ID_ESTUDIANTE`),
  CONSTRAINT `estudiante_has_trastorno_ibfk_2` FOREIGN KEY (`TRASTORNO_ID_TRASTORNO`) REFERENCES `trastorno` (`ID_TRASTORNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `estudiante_has_trastorno` */

LOCK TABLES `estudiante_has_trastorno` WRITE;

UNLOCK TABLES;

/*Table structure for table `evaluacion` */

DROP TABLE IF EXISTS `evaluacion`;

CREATE TABLE `evaluacion` (
  `ID_EVALUACION` int NOT NULL AUTO_INCREMENT,
  `CUALITATIVA_EVALUACION` varchar(45) NOT NULL,
  `CUANTITATIVA_EVALUACION` varchar(45) NOT NULL,
  `CRITERIOS EVALUACION` varchar(45) NOT NULL,
  `EVALUACION_ESTRATEGIA` varchar(45) NOT NULL,
  `BOLETIN_ACADÉMICO_ID_BOLETIN_ACADÉMICO` int NOT NULL,
  PRIMARY KEY (`ID_EVALUACION`),
  KEY `BOLETIN_ACADÉMICO_ID_BOLETIN_ACADÉMICO` (`BOLETIN_ACADÉMICO_ID_BOLETIN_ACADÉMICO`),
  CONSTRAINT `evaluacion_ibfk_1` FOREIGN KEY (`ID_EVALUACION`) REFERENCES `piar` (`EVALUACION_ID_EVALUACION`),
  CONSTRAINT `evaluacion_ibfk_2` FOREIGN KEY (`BOLETIN_ACADÉMICO_ID_BOLETIN_ACADÉMICO`) REFERENCES `boletin_académico` (`ID_BOLETIN_ACADÉMICO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `evaluacion` */

LOCK TABLES `evaluacion` WRITE;

UNLOCK TABLES;

/*Table structure for table `fecha_registro` */

DROP TABLE IF EXISTS `fecha_registro`;

CREATE TABLE `fecha_registro` (
  `ID_FECHA_REGISTRO` int NOT NULL AUTO_INCREMENT,
  `CREACION_REGISTRO` date DEFAULT NULL,
  `ACTUALIZACION_REGISTRO` date DEFAULT NULL,
  PRIMARY KEY (`ID_FECHA_REGISTRO`),
  CONSTRAINT `fecha_registro_ibfk_1` FOREIGN KEY (`ID_FECHA_REGISTRO`) REFERENCES `usuarios` (`ID_USUARIO`),
  CONSTRAINT `fecha_registro_ibfk_2` FOREIGN KEY (`ID_FECHA_REGISTRO`) REFERENCES `matricula` (`FECHA_REGISTRO_ID_FECHA_REGISTRO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `fecha_registro` */

LOCK TABLES `fecha_registro` WRITE;

UNLOCK TABLES;

/*Table structure for table `grado` */

DROP TABLE IF EXISTS `grado`;

CREATE TABLE `grado` (
  `ID_GRADO` int NOT NULL AUTO_INCREMENT,
  `CODIGO_GRADO` varchar(10) NOT NULL,
  `CANTIDAD_ESTUDIANTES` int NOT NULL,
  `INSTITUCION_ID_INSTITUCION` int NOT NULL,
  `MATERIA_ID_MATERIA` int NOT NULL,
  PRIMARY KEY (`ID_GRADO`),
  KEY `MATERIA_ID_MATERIA` (`MATERIA_ID_MATERIA`),
  KEY `INSTITUCION_ID_INSTITUCION` (`INSTITUCION_ID_INSTITUCION`),
  CONSTRAINT `grado_ibfk_1` FOREIGN KEY (`MATERIA_ID_MATERIA`) REFERENCES `materia` (`ID_MATERIA`),
  CONSTRAINT `grado_ibfk_2` FOREIGN KEY (`INSTITUCION_ID_INSTITUCION`) REFERENCES `institucion` (`ID_INSTITUCION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `grado` */

LOCK TABLES `grado` WRITE;

UNLOCK TABLES;

/*Table structure for table `institucion` */

DROP TABLE IF EXISTS `institucion`;

CREATE TABLE `institucion` (
  `ID_INSTITUCION` int NOT NULL AUTO_INCREMENT,
  `NOMBRE_INSTITUCION` varchar(150) NOT NULL,
  `NIT_INSTITUCION` varchar(45) NOT NULL,
  `CORREO_INSTITUCION` varchar(45) NOT NULL,
  `TELEFONO_INSTITUCION` varchar(45) NOT NULL,
  `DIRECCION_INSTITUCION` varchar(150) NOT NULL,
  PRIMARY KEY (`ID_INSTITUCION`),
  CONSTRAINT `institucion_ibfk_1` FOREIGN KEY (`ID_INSTITUCION`) REFERENCES `representante legal` (`ID_REPRESENTANTE LEGAL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `institucion` */

LOCK TABLES `institucion` WRITE;

UNLOCK TABLES;

/*Table structure for table `materia` */

DROP TABLE IF EXISTS `materia`;

CREATE TABLE `materia` (
  `ID_MATERIA` int NOT NULL,
  `CODIGO_MATERIA` varchar(45) NOT NULL,
  `NOMBRE_MATERIA` varchar(45) NOT NULL,
  `DESCRIPCION_MATERIA` tinytext NOT NULL,
  `PLAN_MATERIA` longblob NOT NULL,
  PRIMARY KEY (`ID_MATERIA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `materia` */

LOCK TABLES `materia` WRITE;

UNLOCK TABLES;

/*Table structure for table `matricula` */

DROP TABLE IF EXISTS `matricula`;

CREATE TABLE `matricula` (
  `ID_MATRICULA` int NOT NULL AUTO_INCREMENT,
  `CODIGO_MATRICULA` varchar(45) NOT NULL,
  `VALOR_MATRICULA` decimal(10,2) NOT NULL,
  `FECHA_MATRICULA` date NOT NULL,
  `JORNADA` enum('MAÑANA','TARDE','UNICA') NOT NULL,
  `INSTITUCION_ID_INSTITUCION` int NOT NULL,
  `ESTUDIANTE_ID_ESTUDIANTE` int NOT NULL,
  `FECHA_REGISTRO_ID_FECHA_REGISTRO` int NOT NULL,
  PRIMARY KEY (`ID_MATRICULA`),
  KEY `INSTITUCION_ID_INSTITUCION` (`INSTITUCION_ID_INSTITUCION`),
  KEY `FECHA_REGISTRO_ID_FECHA_REGISTRO` (`FECHA_REGISTRO_ID_FECHA_REGISTRO`),
  KEY `ESTUDIANTE_ID_ESTUDIANTE` (`ESTUDIANTE_ID_ESTUDIANTE`),
  CONSTRAINT `matricula_ibfk_1` FOREIGN KEY (`INSTITUCION_ID_INSTITUCION`) REFERENCES `institucion` (`ID_INSTITUCION`),
  CONSTRAINT `matricula_ibfk_2` FOREIGN KEY (`ESTUDIANTE_ID_ESTUDIANTE`) REFERENCES `estudiante` (`ID_ESTUDIANTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `matricula` */

LOCK TABLES `matricula` WRITE;

UNLOCK TABLES;

/*Table structure for table `novedades_ reportes` */

DROP TABLE IF EXISTS `novedades_ reportes`;

CREATE TABLE `novedades_ reportes` (
  `ID_NOVEDADES_REPORTES` int NOT NULL AUTO_INCREMENT,
  `FECHA_NOVEDADES_ REPORTES` date NOT NULL,
  `NUMERO_DOCUMENTO_ESTUDIANTE` varchar(45) NOT NULL,
  `ACCIONES_NOVEDADES_ REPORTES` text NOT NULL,
  `TIPO_NOVEDADES_ REPORTES` enum('Académica','Conductual','Médica','Psicológica','NuevoEstudianteTEA','Otra') NOT NULL,
  `DESCRIPCION_NOVEDADES_ REPORTES` text NOT NULL,
  `ESTADO_NOVEDADES_ REPORTES` enum('Pendiente','En proceso','Resuelto') NOT NULL DEFAULT 'Pendiente',
  `PRIORIDAD` enum('Alta','Media','Baja') NOT NULL,
  `USUARIOS_ID_USUARIO` int NOT NULL,
  PRIMARY KEY (`ID_NOVEDADES_REPORTES`),
  KEY `USUARIOS_ID_USUARIO` (`USUARIOS_ID_USUARIO`),
  CONSTRAINT `novedades_ reportes_ibfk_1` FOREIGN KEY (`USUARIOS_ID_USUARIO`) REFERENCES `usuarios` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `novedades_ reportes` */

LOCK TABLES `novedades_ reportes` WRITE;

UNLOCK TABLES;

/*Table structure for table `piar` */

DROP TABLE IF EXISTS `piar`;

CREATE TABLE `piar` (
  `CODIGO_PIAR` int NOT NULL AUTO_INCREMENT,
  `PERIODO` varchar(45) NOT NULL,
  `EVALUACION` varchar(200) NOT NULL,
  `DBA` varchar(200) NOT NULL,
  `BARRA_DE_APRENDIZAJE` varchar(200) NOT NULL,
  `FLEXIBILIZACION` varchar(45) NOT NULL,
  `ESTUDIANTE_ID_ESTUDIANTE` int NOT NULL,
  `EVALUACION_ID_EVALUACION` int NOT NULL,
  PRIMARY KEY (`CODIGO_PIAR`),
  KEY `ESTUDIANTE_ID_ESTUDIANTE` (`ESTUDIANTE_ID_ESTUDIANTE`),
  KEY `EVALUACION_ID_EVALUACION` (`EVALUACION_ID_EVALUACION`),
  CONSTRAINT `piar_ibfk_1` FOREIGN KEY (`ESTUDIANTE_ID_ESTUDIANTE`) REFERENCES `estudiante` (`ID_ESTUDIANTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `piar` */

LOCK TABLES `piar` WRITE;

UNLOCK TABLES;

/*Table structure for table `piar_has_estrategias_educativas` */

DROP TABLE IF EXISTS `piar_has_estrategias_educativas`;

CREATE TABLE `piar_has_estrategias_educativas` (
  `CODIGO_PIAR_has_ESTRATEGIAS_EDUCATIVAS` varchar(45) NOT NULL,
  `PIAR_CODIGO_PIAR` int NOT NULL,
  `ESTRATEGIAS_EDUCATIVAS_ID_ESTRATEGIAS_EDUCATIVAS` int NOT NULL,
  `EVALUACIÓN_ESTRATEGIA` varchar(45) NOT NULL,
  PRIMARY KEY (`CODIGO_PIAR_has_ESTRATEGIAS_EDUCATIVAS`),
  KEY `PIAR_CODIGO_PIAR` (`PIAR_CODIGO_PIAR`),
  KEY `ESTRATEGIAS_EDUCATIVAS_ID_ESTRATEGIAS_EDUCATIVAS` (`ESTRATEGIAS_EDUCATIVAS_ID_ESTRATEGIAS_EDUCATIVAS`),
  CONSTRAINT `piar_has_estrategias_educativas_ibfk_1` FOREIGN KEY (`PIAR_CODIGO_PIAR`) REFERENCES `piar` (`CODIGO_PIAR`),
  CONSTRAINT `piar_has_estrategias_educativas_ibfk_2` FOREIGN KEY (`ESTRATEGIAS_EDUCATIVAS_ID_ESTRATEGIAS_EDUCATIVAS`) REFERENCES `estrategias_educativas` (`ID_ESTRATEGIAS_EDUCATIVAS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `piar_has_estrategias_educativas` */

LOCK TABLES `piar_has_estrategias_educativas` WRITE;

UNLOCK TABLES;

/*Table structure for table `protocolos_rutas` */

DROP TABLE IF EXISTS `protocolos_rutas`;

CREATE TABLE `protocolos_rutas` (
  `ID_PROTOCOLOS_RUTAS` int NOT NULL AUTO_INCREMENT,
  `NOMBRE_PROTOCOLOS_RUTAS` varchar(45) NOT NULL,
  `DESCRIPCION_PROTOCOLOS_RUTAS` text NOT NULL,
  `TIPO_PROTOCOLOS_RUTAS` enum('Emergencia','Seguimiento','Psicológico','Otro') NOT NULL,
  `PASOS_PROTOCOLOS_RUTAS` text NOT NULL,
  `RESPONSABLE_PROTOCOLOS_RUTAS` varchar(100) NOT NULL,
  `ESTADO_PROTOCOLOS_RUTAS` enum('Activo','En proceso','Cerrrado') NOT NULL,
  `NOVEDADES_ REPORTES_ID_NOVEDADES_REPORTES` int NOT NULL,
  PRIMARY KEY (`ID_PROTOCOLOS_RUTAS`),
  KEY `NOVEDADES_ REPORTES_ID_NOVEDADES_REPORTES` (`NOVEDADES_ REPORTES_ID_NOVEDADES_REPORTES`),
  CONSTRAINT `protocolos_rutas_ibfk_1` FOREIGN KEY (`NOVEDADES_ REPORTES_ID_NOVEDADES_REPORTES`) REFERENCES `novedades_ reportes` (`ID_NOVEDADES_REPORTES`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `protocolos_rutas` */

LOCK TABLES `protocolos_rutas` WRITE;

UNLOCK TABLES;

/*Table structure for table `representante legal` */

DROP TABLE IF EXISTS `representante legal`;

CREATE TABLE `representante legal` (
  `ID_REPRESENTANTE LEGAL` int NOT NULL AUTO_INCREMENT,
  `NOMBRE_REPRESENTANTE LEGAL` varchar(45) NOT NULL,
  `DOCUMENTO_REPRESENTANTE LEGAL` varchar(20) NOT NULL,
  `TELEFONO_REPRESENTANTE LEGAL` varchar(45) NOT NULL,
  `CORREO_REPRESENTANTE LEGALcol` varchar(45) NOT NULL,
  `INSTITUCION_ID_INSTITUCION` int NOT NULL,
  PRIMARY KEY (`ID_REPRESENTANTE LEGAL`),
  KEY `INSTITUCION_ID_INSTITUCION` (`INSTITUCION_ID_INSTITUCION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `representante legal` */

LOCK TABLES `representante legal` WRITE;

UNLOCK TABLES;

/*Table structure for table `rol` */

DROP TABLE IF EXISTS `rol`;

CREATE TABLE `rol` (
  `ID_ROL` int NOT NULL AUTO_INCREMENT,
  `NOMBRE_ROL` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_ROL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `rol` */

LOCK TABLES `rol` WRITE;

UNLOCK TABLES;

/*Table structure for table `tipo_documento` */

DROP TABLE IF EXISTS `tipo_documento`;

CREATE TABLE `tipo_documento` (
  `ID_TIPO_DOCUMENTO` int NOT NULL AUTO_INCREMENT,
  `NOMBRE_TIPO_DOCUMENTO` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_TIPO_DOCUMENTO`),
  CONSTRAINT `tipo_documento_ibfk_1` FOREIGN KEY (`ID_TIPO_DOCUMENTO`) REFERENCES `usuarios` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `tipo_documento` */

LOCK TABLES `tipo_documento` WRITE;

UNLOCK TABLES;

/*Table structure for table `trastorno` */

DROP TABLE IF EXISTS `trastorno`;

CREATE TABLE `trastorno` (
  `ID_TRASTORNO` int NOT NULL AUTO_INCREMENT,
  `NOMBRE_TRASTORNO` varchar(100) NOT NULL,
  `DESCRIPCIÓN_TRASTORNO` varchar(45) NOT NULL,
  `DIAGNOSTICO_MEDICO_TRASTORNO` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID_TRASTORNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `trastorno` */

LOCK TABLES `trastorno` WRITE;

UNLOCK TABLES;

/*Table structure for table `usuarioprof_has_materia` */

DROP TABLE IF EXISTS `usuarioprof_has_materia`;

CREATE TABLE `usuarioprof_has_materia` (
  `ID_USUARIOPROF_MATERIA` int NOT NULL AUTO_INCREMENT,
  `USUARIOS_ID_USUARIO` int NOT NULL,
  `USUARIOS_ROL_ID_ROL` int NOT NULL,
  `MATERIA_ID_MATERIA` int NOT NULL,
  PRIMARY KEY (`ID_USUARIOPROF_MATERIA`),
  KEY `MATERIA_ID_MATERIA` (`MATERIA_ID_MATERIA`),
  KEY `USUARIOS_ID_USUARIO` (`USUARIOS_ID_USUARIO`),
  CONSTRAINT `usuarioprof_has_materia_ibfk_1` FOREIGN KEY (`MATERIA_ID_MATERIA`) REFERENCES `materia` (`ID_MATERIA`),
  CONSTRAINT `usuarioprof_has_materia_ibfk_2` FOREIGN KEY (`USUARIOS_ID_USUARIO`) REFERENCES `usuarios` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `usuarioprof_has_materia` */

LOCK TABLES `usuarioprof_has_materia` WRITE;

UNLOCK TABLES;

/*Table structure for table `usuarios` */

DROP TABLE IF EXISTS `usuarios`;

CREATE TABLE `usuarios` (
  `ID_USUARIO` int NOT NULL AUTO_INCREMENT,
  `NUMERO_DOCUMENTO` varchar(20) NOT NULL,
  `PRIMER_NOMBRE` varchar(45) NOT NULL,
  `PRIMER_APELLIDO` varchar(45) NOT NULL,
  `TELEFONO_USUARIO` varchar(45) DEFAULT NULL,
  `DIRECCION_USUARIO` tinytext,
  `CORREO_USUARIO` varchar(45) NOT NULL,
  `CORREO_INSTITUCIONAL` varchar(45) NOT NULL,
  `PASSWORD` varchar(45) NOT NULL,
  `ROL_ID_ROL` int NOT NULL,
  `TIPO_DOCUMENTO_ID_TIPO_DOCUMENTO` int NOT NULL,
  `FECHA_REGISTRO_ID_FECHA_REGISTRO` int NOT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  KEY `ROL_ID_ROL` (`ROL_ID_ROL`),
  KEY `TIPO_DOCUMENTO_ID_TIPO_DOCUMENTO` (`TIPO_DOCUMENTO_ID_TIPO_DOCUMENTO`),
  KEY `FECHA_REGISTRO_ID_FECHA_REGISTRO` (`FECHA_REGISTRO_ID_FECHA_REGISTRO`),
  CONSTRAINT `usuarios_ibfk_1` FOREIGN KEY (`ROL_ID_ROL`) REFERENCES `rol` (`ID_ROL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

/*Data for the table `usuarios` */

LOCK TABLES `usuarios` WRITE;

UNLOCK TABLES;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
